Add support for `serde(skip)`
trussed-dev/serde-indexed pull request #14
Opened 2024-02-13 10:34 UTC by sosthene-nitrokey

`skip` causes the index to not be increased to match deserialization from upstream `serde`.

2025-02-16 21:47 UTC, AlfioEmanueleFresta commented
@robin-nitrokey, @sosthene-nitrokey, could this be merged? It would help us address https://github.com/linux-credentials/libwebauthn/issues/74. TIA!

2025-02-16 22:28 UTC, robin-nitrokey commented
Generally yes, but I’m not sure how we should handle indexing with skipped fields.  Not incrementing the index for a skipped field makes sense, but it would silently change the serialization format so we would need to be very careful when upgrading.

Alternatively, we could move to explicit indices (https://github.com/trussed-dev/serde-indexed/issues/17).

@AlfioEmanueleFresta Do you have a preference regarding the index?

2025-02-16 22:37 UTC, AlfioEmanueleFresta commented
Thanks @robin-nitrokey! I agree explicit indexing sounds like the best option. 

Our use case is to skip unused indexes in CTAP spec models (eg. see https://github.com/linux-credentials/libwebauthn/issues/74), so either incrementing the index automatically, or explicit indexing, would be needed.

2025-02-16 22:40 UTC, robin-nitrokey commented
Okay.  I think we could release a v0.1.2 that implements `skip` while incrementing the index and then release a v0.2.0 that splits the derive macro into `SerdeIndexed` with explicit indexing and `SerdeAutoIndexed` with the current behavior.  @sosthene-nitrokey What do you think?

2025-02-17 08:26 UTC, sosthene-nitrokey commented
That sounds good!

2025-02-17 09:45 UTC, robin-nitrokey requested changes

2025-02-17 09:45 UTC, robin-nitrokey commented on src/parse.rs
> +            }
Per the discussion in this thread, we should increment the index even if the field is skipped.

2025-02-17 10:07 UTC, sosthene-nitrokey commented on src/parse.rs
> +            }
I'll add an option to be able to not increment. (Default would be to increment).

2025-06-04 19:27 UTC, merged