Release v0.1.1
trussed-dev/serde-indexed pull request #15
Opened 2024-04-03 13:15 UTC by robin-nitrokey

2024-04-03 13:18 UTC, sosthene-nitrokey requested changes

2024-04-03 13:18 UTC, sosthene-nitrokey commented on Cargo.toml
>  authors = ["Nicolas Stalder <n@stalder.io>"]
```suggestion
version = "0.1.1"
authors = ["Nicolas Stalder <n@stalder.io>", "Trussed Developers"]
```

2024-04-03 13:30 UTC, sosthene-nitrokey approved these changes

2024-04-03 13:40 UTC, robin-nitrokey commented
@nickray Please merge, tag and release v0.1.1.

2024-04-12 09:36 UTC, daringer approved these changes

2024-06-02 10:26 UTC, merged